version: "3"

services:
  with-docker-multi-env-development:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    image: with-docker-multi-env-development
    ports:
      - "3000:3000"